apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-deployment
  labels:
    app: cinewhisper
    component: celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: your-registry/cinewhisper:latest
        command: ["celery", "-A", "cinewhisper", "worker", "--loglevel=info"]
        env:
        - name: DATABASE_URL
          value: "postgres://youruser:yourpassword@postgres-service:5432/yourdb"
        - name: CELERY_BROKER_URL
          value: "redis://redis-service:6379/0"
        - name: DJANGO_SETTINGS_MODULE
          value: "cinewhisper.settings"

