apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat-deployment
  labels:
    app: cinewhisper
    component: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: your-registry/cinewhisper:latest
        command: ["celery", "-A", "cinewhisper", "beat", "--loglevel=info"]
        env:
        - name: DATABASE_URL
          value: "postgres://youruser:yourpassword@postgres-service:5432/yourdb"
        - name: CELERY_BROKER_URL
          value: "redis://redis-service:6379/0"
        - name: DJANGO_SETTINGS_MODULE
          value: "cinewhisper.settings"

