apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinewhisper-deployment
  labels:
    app: cinewhisper
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cinewhisper
  template:
    metadata:
      labels:
        app: cinewhisper
    spec:
      containers:
      - name: cinewhisper
        image: your-registry/cinewhisper:latest  # Push your Docker image here
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgres://youruser:yourpassword@postgres-service:5432/yourdb"
        - name: CELERY_BROKER_URL
          value: "redis://redis-service:6379/0"
        - name: DJANGO_SETTINGS_MODULE
          value: "cinewhisper.settings"

